classviewcrud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('core.urls', namespace = 'core')),
]

core/urls.py
from django.urls import path
from . import views


app_name    =   'core'

urlpatterns = [
    path ('', views.IndexView.as_view(), name='index'),
    path ('add/', views.AddView.as_view(), name='add'),
    path ('polls/<int:pk>/', views.PollsView.as_view(), name='polls'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete')
    
]

core/models.py
from django.db import models

# Create your models here.

from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class Core(models.Model):
    poll_title          =   models.CharField (max_length=200)
    description         =   models.TextField(null=True)
    author              =   models.ForeignKey(User, on_delete=models.CASCADE, related_name='core')    
    updated             =   models.DateTimeField(auto_now=True)
    published           =   models.DateTimeField(default=timezone.now)   

    class Meta:
        ordering    =   ['-published']

    def __str__(self):
        return self.poll_title

class Currentpolls(models.Model):
    currentUser         =   models.CharField(max_length=20)
    pollID              =   models.IntegerField(default=0)
    pollComments        =   models.CharField(max_length=200)
    commentsDate        =   models.DateTimeField(auto_now =True)   


    

core/forms.py
from django import froms
from .models import Core

class PostForm(forms.modelForm):
    class Meta:
        model   =   Core
        fields  =   "__all__"

core/views.py
from .models import Core
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy


class IndexView(ListView):
    model               =   Core
    template_name       =   'core/index.html'
    paginate_by         =   10
    context_object_name =   'post_list'

class PollsView(DetailView):
    model               =   Core
    template_name       =   'core/polls.html'
    pk_url_kwarg        =   'pk'
    context_object_name =   'poll'



class AddView(CreateView):
    model               =   Core
    template_name       =   'core/add.html'
    fields              =   '__all__'
    success_url         =   reverse_lazy('core:index')

class EditView(UpdateView):
    model               =   Core
    template_name       =   'core/edit.html'
    fields              =   '__all__'
    pk_url_kwarg        =   'pk'
    success_url         =   reverse_lazy('core:index')

class Delete(DeleteView):
    model               =   Core    
    # fields              =   '__all__'
    pk_url_kwarg        =   'pk'
    success_url         =   reverse_lazy('core:index')
    template_name       =   'core/confirm-delete.html'

templates/core/add.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container pt-5">
      <form method="post" novalidate>
          {% csrf_token %}

          {% for field in form.visible_fields %}
            <div class="form-group">
                <label for ="{{  field.id_for_label }}"> {{ field.label }}  </label>
                {{field|add_class:'form-control'}}
                {% for error in field.errors %}
                <span class="help-block"> {{ error }}</span> 
                {% endfor %}
            </div>
          {% endfor %}
          <div class="form-group">
              <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Save
              </button>
              <a href="{% url 'core:index' %}" class="btn btn-danger">Cancel</a>
          </div>
      </form>
    </div>
</div>



{% endblock %}

templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>CRUD App</title>
  </head>
  <body>

    {% include 'core/navbar.html' %}
    {% block content %}

    {% endblock %}
    {% include 'core/footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/core/confirm-delete.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class='container pt-5'>

  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" class="btn btn-light">
    <a href="{% url 'core:index' %}" class="btn btn-light">Cancel</a>
  </form>
</div>

{% endblock %}

templates/core/edit.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container pt-5">
      <form method="post" novalidate>
          {% csrf_token %}

          {% for field in form.visible_fields %}
            <div class="form-group">
                <label for ="{{  field.id_for_label }}"> {{ field.label }}  </label>
                {{field|add_class:'form-control'}}
                {% for error in field.errors %}
                <span class="help-block"> {{ error }}</span> 
                {% endfor %}
            </div>
          {% endfor %}
          <div class="form-group">
              <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Update
              </button>
              <a href="{% url 'core:index' %}" class="btn btn-danger">Cancel</a>
          </div>
      </form>
    </div>
</div>



{% endblock %}

templates/core/footer.html
<!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container my-5">

    <footer class="bg-dark text-center text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-facebook-f"></i
        ></a>
  
        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-twitter"></i
        ></a>
  
        <!-- Google -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-google"></i
        ></a>
  
        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-instagram"></i
        ></a>
  
        <!-- Linkedin -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-linkedin-in"></i
        ></a>
  
        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
          ><i class="fab fa-github"></i
        ></a>
      </section>
      <!-- Section: Social media -->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2020 Copyright:
      <a class="text-white" href="#">Testing</a>
    </div>
    <!-- Copyright -->
  </footer>
    
  </div>
  <!-- End of .container -->

templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}


<div class="album py-5 bg-light">
    <div class="container-fluid">
        <h1 class="text-center ">CURRENT POLLS</h1>
        <div class="row">
            
                
                        <div class="col-lg-2"></div>
                            <div class="col-lg-8">
                            {% for post in post_list %}
                                <div class="card mb-4 box-shadow">
                                    <div class = "card-body">
                                        <h4 class="lead"> <a class="text-dark" href="{% url 'core:polls' post.pk %}"> {{ post.poll_title }} </a> </h4>
                                        <small class="text-muted">Author: {{post.author}}</small>
                                        
                                        <div class="d-flex justify-content-between align-items-center mt-2">
                                            <div class="btn-group">
                                                <a href="{% url 'core:polls' post.pk %}" class="btn btn-sm btn-outline-primary" role="button" aria-pressed="true">View</a>
                                                <a href="{% url 'core:edit' post.pk %}" class="btn btn-sm btn-outline-primary" role="button" aria-pressed="true">Edit</a>
                                                <a href="{% url 'core:delete' post.pk %}" class="btn btn-sm btn-outline-primary" role="button" aria-pressed="true">Delete</a>
                                            </div>                                
                                        </div>  
                                    </div>
                                </div>                        
                            {% endfor %}
                                <ul class="pagination">

                                    {% if page_obj.has_previous %}
                                        <li class="page-item"><a href="?page=1" class="page-link" >&laquo; First</a></li>
                                        <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a></li>
                                    {% endif %}
                    
                                    {% if page_obj.has_next %}
                                        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a></li>
                                        <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">&raquo;Last</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                        <div class="col-lg-2"></div>
                
            
        
            
        </div>
    </div>
</div>



{% endblock %}

templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top text">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/add">Add Poll</a>
    </div>
  </div>
</nav>

templates/core/polls.html
 {% extends 'core/base.html' %}

 {% block content %}
 
 <div class="container-fluid">
     <div class="row">
        <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <h2 class="pt-5">{{ poll.poll_title }}</h2>
                <small class="text-muted">Author: {{poll.author}}</small>
                
            </div>

        <div class="col-lg-2"></div>
     </div>
 </div>

 {% endblock %}